### ISSUE TITLE
Fails on empty update

### ISSUE THREAD

**Issue by chrismilson** [MichaelHettmer/react-hooks-use-previous#7]
**Bug Description**
The hook will return a value that I would not consider to be the previous value of a supplied prop.

**To Reproduce**
run the test
```ts
it('should not update on rerender if prop is unchanged', () => {
  const { result, rerender } = renderHook(() => usePrevious('current', 'initial'));

  rerender();

  expect(result.current).not.toBe('current');
});
```

**Suggested Fix**
Instead of using useEffect, use a simple if statement to check for update (similarly to how useEffect checks its own array, effectively cutting out the middleman)

**Comment by MichaelHettmer** [comment]
Nice catch. Thank you for this detailed and well written issue / pr!
Merged and released to npm.

**Comment by MichaelHettmer** [comment]
@all-contributors please add @chrismilson for code bug test
